
[target.nanosplus]
runner = "speculos.py --model nanosp --display qt -a 1 --apdu-port 1237 --zoom 2"

[target.nanox]
runner = "speculos.py --model nanox --display qt -a 1 --apdu-port 1237 --zoom 2"

[build]
target = "nanosplus"
rustflags = [
    "-Z", "emit-stack-sizes",
    "-Clink-args=-Map=/tmp/ledger-mob.map",
]

[unstable]
build-std = [ "core", "compiler_builtins", "alloc" ]

[alias]
br = "build --release"
stackcheck = "call-stack --bin ledger-mob-fw --target nanosplus sample_main"

[env]
RUST_TARGET_PATH = { value = "../../vendor/sdk", relative = true }
